const Images = {
    splashScreenImage: require('../../assets/Images/SplashScreenImage.png'),
    homeIcon: require('../../assets/Images/Home.png'),
    categoriesIcon: require('../../assets/Images/Categories.png'),
    offersIcon: require('../../assets/Images/Offers.png'),
    wishlistIcon: require('../../assets/Images/Wishlist.png'),
    cartIcon: require('../../assets/Images/Cart.png'),
    searchIcon: require('../../assets/Images/Search.png'),
    proMartLogo: require('../../assets/Images/ProMartLogo.png'),
    locationIcon: require('../../assets/Images/Location.png'),
    nearByImage: require('../../assets/Images/NearBy.png'),
    downArrowIcon: require('../../assets/Images/DownArrow.png'),
    rightArrowIcon: require('../../assets/Images/RightArrow.png'),
    starIcon: require('../../assets/Images/Star.png'),

    // Static Images
    staticImage: require('../../assets/Images/static.jpg'),
    groceryImage: require('../../assets/Images/Grocery.png'),
    oatsImage: require('../../assets/Images/Oats.png'),
    bagsImage: require('../../assets/Images/Bags.png'),
    demo1Image: require('../../assets/Images/Demo1.png'),
    demo2Image: require('../../assets/Images/Demo2.png'),
    demo3Image: require('../../assets/Images/Demo3.png'),
    demo4Image: require('../../assets/Images/Demo4.png'),
    demo5Image: require('../../assets/Images/Demo5.png'),
    demo6Image: require('../../assets/Images/Demo6.png'),
    demo7Image: require('../../assets/Images/Demo7.png'),
    demo8Image: require('../../assets/Images/Demo8.png'),
    demo9Image: require('../../assets/Images/Demo9.png'),
    demo10Image: require('../../assets/Images/Demo10.png'),
    demo11Image: require('../../assets/Images/Demo11.png'),
    demo12Image: require('../../assets/Images/Demo12.png'),
    demo13Image: require('../../assets/Images/Demo13.png'),
    demo14Image: require('../../assets/Images/Demo14.png'),
    demo15Image: require('../../assets/Images/Demo15.png'),
    demo16Image: require('../../assets/Images/Demo16.png'),
    demo17Image: require('../../assets/Images/Demo17.png'),
    demo18Image: require('../../assets/Images/Demo18.png'),
    demo19Image: require('../../assets/Images/Demo19.png'),
};

export default Images;
